name: Compare genesis with bytecode files from BSC repo
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - master
      - develop
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  check-keyword:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, ' hardfork]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run your CI script
        run: echo ${{github.event.pull_request.title}}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run your CI script
        run: echo "Test"
